#!/bin/bash

case ${1} in
    b | build )
        VERSION=$(date +'%s')
        DOCKER_CONTEXT="$(dirname "$0")"
        docker build -t digital-diary-database:${VERSION} -f ${DOCKER_CONTEXT}/Dockerfile ${DOCKER_CONTEXT}
        docker tag digital-diary-database:${VERSION} digital-diary-database:latest
        ;;
    r | run )
        docker run -d -p 5432:5432 -v digital-diary:/var/lib/postgresql/data digital-diary-database:latest
        ;;
    s | stop )
        CONTAINER_ID=$(docker ps -q -f=ancestor=digital-diary-database:latest)
        ! [ -z ${CONTAINER_ID} ] && docker stop ${CONTAINER_ID}
        ;;
    clean )
        docker rm $(docker ps -qa -f ancestor=digital-diary-database) 2> /dev/null
        docker rmi -f $(docker images -qa digital-diary-database) 2> /dev/null
        ;;
    * )
        echo -e "Basic actions with postgres database container"
        echo -e "\nCommands:"
        echo -e "  b, build\tBuild and tag image as latest"
        echo -e "  r, run\tRun pg database image tagged as latest"
        echo -e "  s, stop\tStop running pg database container"
        echo -e "  clean\t\tRemove images and containers"
esac
