#!/usr/bin/env bash

function print_help() {
    echo -e "Commands:"
    echo -e "  g, generate\tRegenerate openapi documentation"
    echo -e "  i, install\tInstall globally openapi-generator-cli package"
    echo -e "  u, clean\tRemove globally openapi-generator-cli package"
}

function check_command_exists() {
    if [[ -z $(command -v openapi-generator) ]]; then
        echo -e "Unable to find openapi-generator-cli\n" >&2
        print_help
        exit 1
    fi
}

case $1 in

    i | install)
        sudo npm i -g @openapitools/openapi-generator-cli
        ;;

    g | generate )
        check_command_exists

        CONTEXT=$(dirname $0)/../backend

        # Remove old files
        rm -rf ${CONTEXT}/generated/openapi

        openapi-generator generate -g html2 \
            -i ${CONTEXT}/openapi.yaml \
            -o ${CONTEXT}/generated/openapi

        # Remove useless files
        rm -rf ${CONTEXT}/generated/openapi/.openapi-generator*
        ;;

    u | uninstall )
        sudo npm uninstall -g @openapitools/openapi-generator-cli
        ;;

    * )
        if [[ ${1} ]]; then echo -e "Unknown command: $1\n"; fi
        print_help
esac